# Generated by Django 4.1.1 on 2022-09-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donalds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='amount',
        ),
        migrations.AddField(
            model_name='productorder',
            name='_amount',
            field=models.IntegerField(default=1),
        ),
    ]
